name: tags

on:
  push:
    tags:
      - 'v*'

env:
  EXECUTABLE_NAME: tgnotifier
  EXECUTABLE_NAME_WINDOWS: tgnotifier.exe
  GO_VERSION: '1.24'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Test
        run: make test

      - name: Lint
        run: make lint

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    runs-on: ${{ matrix.os }}
    env:
      ARTIFACT_NAME: tgnotifier_${{ github.ref_name }}_${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: make build

      - name: Upload executable artifact
        if: matrix.os != 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: tgnotifier
          if-no-files-found: error

      - name: Upload Windows executable artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: tgnotifier.exe
          if-no-files-found: error

  autorelease:
    name: Create Release
    runs-on: 'ubuntu-latest'
    needs: [validate, build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}
          pattern: tgnotifier_${{ github.ref_name }}_*
          merge-multiple: true

      - name: Print artifacts
        run: ls -R ${{ github.workspace }}

      - name: Create draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          gh release create ${{ github.ref_name }} ${{ github.workspace }}/tgnotifier*
          --title "${{ github.ref_name }}"
          --generate-notes
          --draft