name: tags

on:
  push:
    tags:
      - 'v*'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Test
        run: make test

      - name: Lint
        run: make lint

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build
        run: make build

      - name: Upload executable artifact
        if: matrix.os != 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: tgnotifier_${{ github.ref_name }}_${{ matrix.os }}
          path: tgnotifier

      - name: Upload Windows executable artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: tgnotifier_${{ github.ref_name }}_${{ matrix.os }}
          path: tgnotifier.exe

  autorelease:
    name: Create Release
    runs-on: 'ubuntu-latest'
    needs: [validate, build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: tgnotifier_${{ github.ref_name }}_*
          merge-multiple: true

      - name: Create draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          gh release create ${{ github.ref_name }} ./dist/tgnotifier_${{ github.ref_name }}_*
          --title "${{ github.ref_name }}"
          --generate-notes
          --draft